title: Yoonsu Chang's Homepage
page-top-title: Yoonsu Chang
top-section-bg-text: Yoonsu Chang
home-subtitle: Yoonsu Chang&ensp;|&ensp;장윤수
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
